# Generated by Django 3.0.7 on 2020-08-05 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_image', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='photo',
            field=models.ImageField(upload_to='document/'),
        ),
    ]
