# Generated by Django 3.0.7 on 2020-09-05 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_image', '0003_document_bw_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='sample_numver',
            field=models.IntegerField(default=0),
        ),
    ]
