# Generated by Django 3.0.7 on 2020-09-05 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_image', '0004_document_sample_numver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='sample_numver',
            new_name='sample_number',
        ),
    ]
