# Generated by Django 3.0.7 on 2020-09-05 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_image', '0005_auto_20200905_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='photo',
            field=models.ImageField(unique=True, upload_to='document/'),
        ),
    ]
