version: '3'

services:
  app:
    build: .
    container_name: django-gunicorn
    # env_file:
    #   - django.env
    # ports:
    #   - "8000:8000"
    volumes:
      - ./:/usr/src/app/
      - /home/ubuntu/deploy_test/static:/static
      - /home/ubuntu/deploy_test/media:/media
      - /home/ubuntu/deploy_test/log/django:/log
      # - gunicorn:/var/run/gunicorn
    command:
      # "bash"
      "gunicorn --bind=0.0.0.0:8000 config.wsgi:application -w 2"
      # unix domain socket
      # "gunicorn --bind=unix:/var/run/gunicorn/gunicorn.sock config.wsgi:application"
    expose:
      - 8000
    # extra_hosts:
    #   - "local_dev:172.17.0.1"

  nginx:
    build: ../nginx
    container_name: nginx_test
    volumes:
      - /home/ubuntu/deploy_test/nginx/templates:/etc/nginx/conf.d
      - /home/ubuntu/deploy_test/static:/static
      - /home/ubuntu/deploy_test/media:/media
      - /home/ubuntu/deploy_test/log/nginx:/log
      - /home/ubuntu/deploy_test/nginx/.htpasswd:/etc/nginx/.htpasswd
      # - gunicorn:/var/run/gunicorn
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    depends_on: 
      - app

# unix domain socket
# volumes:
#   gunicorn:
#     driver: local
